### ISSUE TITLE
No carga partida

### ISSUE THREAD

**Issue by Axel5333** [Proyecto-Integral-Web/148781#1]
https://github.com/Proyecto-Integral-Web/148781/blob/509a2e5e45cbdef7eda24cb039c5142d8ad08e01/practiquishaa_vue/src/views/Juego/Juego.vue#L5

**Comment by Axel5333** [comment]
Otra cosa profe, en mi firebase no se me crean otras partidas
las partidas que se me mostraban eran las que habíamos creado en el firebase
pero igual poniendo su código en mi proyecto no muestra nada

**Comment by betoflakes** [comment]
Sabes que tuve un problema parecido, recomiendo que crees una nueva colección y ahora ahí agregar las partidas, la colección juego-1 de pronto dejo de funcionar.

**Comment by betoflakes** [comment]
[Así cargamos todas las partidas](https://github.com/Proyecto-Integral-Web/PaperScissorsRock/blob/40ea34645293281906ff02a6532c98fca67e057a/src/components/Juego/Partidas.vue#L122)

Recuerda que primero hay que tener la lista con todas las partidas.

**Comment by betoflakes** [comment]
Y para cargar la partida estamos utilizando esta opción: [beforeRouteEnter y beforeRouteUpdate](https://github.com/Proyecto-Integral-Web/PaperScissorsRock/blob/40ea34645293281906ff02a6532c98fca67e057a/src/components/Juego/Partida.vue#L76)
